name: Package
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: ./package
      - uses: actions/upload-artifact@v2
        with:
            name: saguarospace-bbedit-utils.tar.gz
            path: saguarospace-bbedit-utils.tar.gz